build:
  maven:
    podyaml: podTemplate-maven.yaml
    image: maven:3-amazoncorretto-17
    steps:
      - "mvn -version"
      - "mvn clean install"
  kaniko:
    podyaml: podTemplate-maven.yaml
    image: gcr.io/kaniko-project/executor:debug
    steps:
      - "mvn version"
      - "mvn clean install"
